### ISSUE TITLE
Add prototype for generating Swift bindings

### ISSUE THREAD

**Issue by linacambridge** [rfk/uniffi-rs#1]
Mainly as an exercise to get familiar with uniffi! 😊

**Comment by linacambridge** [comment]
Things that make Swift interesting, a living list...

* We need to generate two files: a bridging header with C forward declarations, and the Swift file itself.

**Comment by rfk** [comment]
Oh hi! 😁  👋 

A braindump of how I think a successful addition of a new language binding generator would go:

* Take a peek at the python binding generator in `./src/bindings/python`; not because it's the best, but because it's the smallest.
* Observe that you'll roughly need the following support infra implemented in the host language:
    * a `RustBuffer` struct for safely interacting with buffers allocated and returned by the rust code.
    * the ability to serialize and deserialize primitive data types from such a buffer (in the code this says "lift from" and "lower into", which is based on terminology from Wasm Interface Types)
* With that in place, you need to do five things in the binding:
    * Walk the list of FFI function declarations, and generate appropriate host language code to expose each function from the underlying C lib.
    * Walk the list of enum definitions, and emit whatever host-language-appropriate data structure should be used for an enum (with support code to lift and lower it across the FFI)
    * Walk the list of record definitions, and emit whatever host-language-appropriate data structure should be used for such stateless data classes (with support code to lift and lower it across the FFI)
    * Walk the list of top-level functions, and emit whatever host-language-appropriate equivalent there is to a top-level function, lowering the given arguments to their FFI equivalents, calling out to the one loaded from the underlying C-lib, and lifting the result back into the host language.
    * Walk the list of top-level object definitions, and emit whatever host-language-appropriate equivalent there is to a wrapper class with an opaque integer handle.
        * Walk each object's list of method definitions and generate a matching host-language method, lowering the given arguments to their FFI equivalents, passing the handle as first argument, calling out to the one loaded from the underlying C-lib, and lifting the result back into the host language.
* Add support for the new host language to the bindings helper in `./src/lib.rs`, which needs:
    * A function for generating the bindings from the IDL and writing them into the target dir
    * A function to help run scripts in the target language, with appropriate env vars set to make ti automagically pick up things from the target dir
* Go through each of the examples in turn, copy the existing `example.py` or `example.kts` file and make a version for your new host language, then see if you can get `cargo run -- exec example.swift` or equivalent to run successfully!

**Comment by rfk** [comment]
This landed 🎉
